name: Deploy

on:
  push:
    tags:
      - "v*"

jobs:
  docker:
    runs-on: ubuntu-latest
    outputs:
      image-tag: ${{ vars.DOCKERHUB_USERNAME }}/ses-email-forwarder:${{ github.ref_name }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v4
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v7
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ vars.DOCKERHUB_USERNAME }}/ses-email-forwarder:${{ github.ref_name }}
            ${{ vars.DOCKERHUB_USERNAME }}/ses-email-forwarder:latest

  terraform:
    needs: docker
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v4
        with:
          terraform_version: 1.9.8

      - name: Terraform init
        run: |
          terraform -chdir=infra init
      - name: Terraform plan and apply
        env:
          TF_VAR_lambda_image_uri: ${{ needs.docker.outputs.image-tag }}
          TF_VAR_forward_addresses: ${{ vars.FORWARD_ADDRESSES_JSON }}
          TF_VAR_ses_recipient_addresses: ${{ vars.SES_RECIPIENT_ADDRESSES_JSON }}
        run: |
          terraform -chdir=infra plan
          terraform -chdir=infra apply -auto-approve
